version: '3.5'
services:
  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./products-service:/usr/src/app

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./orders-service:/usr/src/app
      
  zuul:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"